// AUTO-GENERATED by scripts/stripe-setup.ts — do not edit by hand.
// Re-run `pnpm tsx scripts/stripe-setup.ts` after any change to
// lib/billing/catalog.ts to regenerate. Generated against the LIVE mode
// of the LeaseStack Stripe account (acct_*).
//
// This file is the source of truth at runtime: lookup_key → Stripe price ID.
// Checked into git so deployments don't need to re-discover IDs and so
// the dashboard always reflects the same catalog the code is wired to.

export const STRIPE_PRICE_IDS = {
  "ls_ad_management_per_dollar_v1": "price_1TWJylIDmE4BmF76rMca6kmI",
  "ls_email_overage_per_send_v1": "price_1TWJykIDmE4BmF76j42ijbB5",
  "ls_extra_creative_v1": "price_1TWJyiIDmE4BmF76SVyxwihJ",
  "ls_foundation_addl_annual_v1": "price_1TWJyaIDmE4BmF76QvJiW3YQ",
  "ls_foundation_addl_monthly_v1": "price_1TWJyaIDmE4BmF76dSBRpTuq",
  "ls_foundation_annual_v1": "price_1TWJyaIDmE4BmF76O9cgWxV9",
  "ls_foundation_monthly_v1": "price_1TWJyaIDmE4BmF76OIeYg8SQ",
  "ls_foundation_setup_v1": "price_1TWJybIDmE4BmF76wWLrY7F6",
  "ls_growth_addl_annual_v1": "price_1TWJycIDmE4BmF76G8hsyDlT",
  "ls_growth_addl_monthly_v1": "price_1TWJycIDmE4BmF76KOdbhDLs",
  "ls_growth_annual_v1": "price_1TWJycIDmE4BmF76toUKV9m1",
  "ls_growth_monthly_v1": "price_1TWJybIDmE4BmF76laNl77C5",
  "ls_growth_setup_v1": "price_1TWJydIDmE4BmF76U3DYlZ9Q",
  "ls_pixel_overage_per_visitor_v1": "price_1TWJyjIDmE4BmF76u2TuHBGp",
  "ls_premium_sla_monthly_v1": "price_1TWJyhIDmE4BmF76HVMcUDPN",
  "ls_quarterly_strategy_v1": "price_1TWJyhIDmE4BmF76bpD6RZby",
  "ls_reputation_pro_monthly_v1": "price_1TWJygIDmE4BmF76hoFXOkKH",
  "ls_scale_addl_annual_v1": "price_1TWJyfIDmE4BmF76ZCiZ9lk4",
  "ls_scale_addl_monthly_v1": "price_1TWJyeIDmE4BmF76d3slfvK5",
  "ls_scale_annual_v1": "price_1TWJyeIDmE4BmF766YwmP6hJ",
  "ls_scale_monthly_v1": "price_1TWJydIDmE4BmF76i8xWoIm5",
  "ls_scale_setup_v1": "price_1TWJyfIDmE4BmF76qlODXZ0z",
  "ls_video_shoot_v1": "price_1TWJyjIDmE4BmF76S9koCnPj",
  "ls_white_label_monthly_v1": "price_1TWJygIDmE4BmF76ISWRlzUA",
} as const;

export type StripeLookupKey = keyof typeof STRIPE_PRICE_IDS;

export const STRIPE_MODE = "LIVE";
