// AUTO-GENERATED by scripts/stripe-setup.ts — do not edit by hand.
// Re-run `pnpm tsx scripts/stripe-setup.ts` after any change to
// lib/billing/catalog.ts to regenerate. Generated against the TEST mode
// of the LeaseStack Stripe account (acct_*).
//
// This file is the source of truth at runtime: lookup_key → Stripe price ID.
// Checked into git so deployments don't need to re-discover IDs and so
// the dashboard always reflects the same catalog the code is wired to.

export const STRIPE_PRICE_IDS = {
  "ls_ad_management_per_dollar_v1": "price_1TWJcQIDmE4BmF766PKcBs80",
  "ls_email_overage_per_send_v1": "price_1TWJcPIDmE4BmF76uZHbXDTV",
  "ls_extra_creative_v1": "price_1TWJbEIDmE4BmF76RaGAIwJ4",
  "ls_foundation_addl_annual_v1": "price_1TWJb7IDmE4BmF769sWgT7Vg",
  "ls_foundation_addl_monthly_v1": "price_1TWJb7IDmE4BmF76Wdxbvo9f",
  "ls_foundation_annual_v1": "price_1TWJb7IDmE4BmF76884UrL7h",
  "ls_foundation_monthly_v1": "price_1TWJb6IDmE4BmF7637BlZJHY",
  "ls_foundation_setup_v1": "price_1TWJb7IDmE4BmF76HTVLisrR",
  "ls_growth_addl_annual_v1": "price_1TWJb9IDmE4BmF76VS3vfTow",
  "ls_growth_addl_monthly_v1": "price_1TWJb8IDmE4BmF76ilo2Upal",
  "ls_growth_annual_v1": "price_1TWJb8IDmE4BmF76xZUcT901",
  "ls_growth_monthly_v1": "price_1TWJb8IDmE4BmF766Lx475KD",
  "ls_growth_setup_v1": "price_1TWJb9IDmE4BmF76RnEUqPNC",
  "ls_pixel_overage_per_visitor_v1": "price_1TWJcOIDmE4BmF76O3Ab5S7D",
  "ls_premium_sla_monthly_v1": "price_1TWJbDIDmE4BmF76uvG3Z4ap",
  "ls_quarterly_strategy_v1": "price_1TWJbDIDmE4BmF76Rr09rzil",
  "ls_reputation_pro_monthly_v1": "price_1TWJbBIDmE4BmF76PtrPxiZd",
  "ls_scale_addl_annual_v1": "price_1TWJbBIDmE4BmF76B7FVU3dF",
  "ls_scale_addl_monthly_v1": "price_1TWJbAIDmE4BmF76YiAHC5aF",
  "ls_scale_annual_v1": "price_1TWJbAIDmE4BmF76F0ciEOVI",
  "ls_scale_monthly_v1": "price_1TWJbAIDmE4BmF76BMEyAZJn",
  "ls_scale_setup_v1": "price_1TWJbBIDmE4BmF768UuaOHZU",
  "ls_video_shoot_v1": "price_1TWJbEIDmE4BmF76OMPAv3ML",
  "ls_white_label_monthly_v1": "price_1TWJbCIDmE4BmF76YeNYrPwE",
} as const;

export type StripeLookupKey = keyof typeof STRIPE_PRICE_IDS;

export const STRIPE_MODE = "TEST";
