// AUTO-GENERATED by scripts/stripe-setup.ts — do not edit by hand.
// Re-run `pnpm tsx scripts/stripe-setup.ts` after any change to
// lib/billing/catalog.ts to regenerate. Generated against the LIVE mode
// of the LeaseStack Stripe account (acct_*).
//
// This file is the source of truth at runtime: lookup_key → Stripe price ID.
// Checked into git so deployments don't need to re-discover IDs and so
// the dashboard always reflects the same catalog the code is wired to.

export const STRIPE_PRICE_IDS = {
  "ls_email_overage_per_send_v1": "price_1TWJykIDmE4BmF76j42ijbB5",
  "ls_foundation_annual_v1": "price_1TWKAZIDmE4BmF76dyi4boTG",
  "ls_foundation_graduated_annual_v1": "price_1TWLZWIDmE4BmF76gUoN0YC1",
  "ls_foundation_graduated_monthly_v1": "price_1TWLZVIDmE4BmF76pMCUW7Xj",
  "ls_foundation_monthly_v1": "price_1TWKAYIDmE4BmF76hWYF1G7J",
  "ls_growth_annual_v1": "price_1TWJycIDmE4BmF76toUKV9m1",
  "ls_growth_graduated_annual_v1": "price_1TWLZXIDmE4BmF76zMkw7Cfq",
  "ls_growth_graduated_monthly_v1": "price_1TWLZWIDmE4BmF76bwPJeOFa",
  "ls_growth_monthly_v1": "price_1TWJybIDmE4BmF76laNl77C5",
  "ls_pixel_overage_per_visitor_v1": "price_1TWJyjIDmE4BmF76u2TuHBGp",
  "ls_reputation_pro_monthly_v1": "price_1TWJygIDmE4BmF76hoFXOkKH",
  "ls_scale_annual_v1": "price_1TWKBpIDmE4BmF76sWgnURcx",
  "ls_scale_graduated_annual_v1": "price_1TWLZYIDmE4BmF76Hyx8m3ZN",
  "ls_scale_graduated_monthly_v1": "price_1TWLZXIDmE4BmF76I0XyqsCK",
  "ls_scale_monthly_v1": "price_1TWJydIDmE4BmF76i8xWoIm5",
  "ls_white_label_monthly_v1": "price_1TWJygIDmE4BmF76ISWRlzUA",
} as const;

export type StripeLookupKey = keyof typeof STRIPE_PRICE_IDS;

export const STRIPE_MODE = "LIVE";
