/**
 * tc-demo-cleanup — REMOVES every row seeded by tc-demo-prep.ts.
 *
 * Targets only rows tagged with externalSystem="tc-demo-prep" so legit
 * data (real chatbot leads, real AppFolio imports, real visitors) is
 * never touched.
 *
 * What it does:
 *   1. Deletes Tour rows with externalSystem="tc-demo-prep"
 *   2. Deletes Lead rows with externalSystem="tc-demo-prep"
 *   3. Reverts the 5 ContentDraft rows from PENDING_REVIEW back to
 *      GENERATING so the admin queue stays honest (operator hasn't
 *      submitted them yet).
 *   4. Optionally also resets the MonthlyContentQuota counts to match
 *      actual draft counts (idempotent — re-runs cleanly).
 *
 * Run:
 *   DATABASE_URL=<unpooled-prod-url> ./node_modules/.bin/tsx scripts/tc-demo-cleanup.ts
 */

import { prisma } from "../lib/db";
import { DraftStatus } from "@prisma/client";

const ORG_ID = "cmo402dwz0002c93lf3okkgi0"; // SG Real Estate
const MARKER = "tc-demo-prep";

(async () => {
  console.log("=== TC demo cleanup starting ===\n");

  // 1. Delete tours first (they reference leads).
  const toursToDelete = await prisma.tour.findMany({
    where: { externalSystem: MARKER },
    select: { id: true, leadId: true },
  });
  if (toursToDelete.length > 0) {
    const tourResult = await prisma.tour.deleteMany({
      where: { externalSystem: MARKER },
    });
    console.log(`[1/3] Deleted ${tourResult.count} fabricated Tour rows.`);
  } else {
    console.log("[1/3] No fabricated Tour rows found.");
  }

  // 2. Delete leads.
  const leadsToDelete = await prisma.lead.findMany({
    where: { externalSystem: MARKER, orgId: ORG_ID },
    select: { id: true, email: true, firstName: true, lastName: true },
  });
  if (leadsToDelete.length > 0) {
    console.log(`[2/3] About to delete ${leadsToDelete.length} fabricated Lead rows:`);
    for (const l of leadsToDelete) {
      console.log(`        · ${l.firstName} ${l.lastName} <${l.email}>`);
    }
    const leadResult = await prisma.lead.deleteMany({
      where: { externalSystem: MARKER, orgId: ORG_ID },
    });
    console.log(`        Deleted ${leadResult.count} fabricated Lead rows.`);
  } else {
    console.log("[2/3] No fabricated Lead rows found.");
  }

  // 3. Revert the 5 PENDING_REVIEW drafts back to GENERATING.
  //
  // Rationale: the underlying draft CONTENT is legitimate (it was
  // generated by Anthropic from real SiteIntelligence + AEO data via the
  // existing prefill-tc-content.ts script). But we elevated their status
  // from GENERATING -> PENDING_REVIEW which implies the OPERATOR submitted
  // them for admin review. They never did. Roll back the status change so
  // the admin queue doesn't show a submission that never happened.
  const draftResult = await prisma.contentDraft.updateMany({
    where: {
      orgId: ORG_ID,
      status: DraftStatus.PENDING_REVIEW,
      submittedAt: { not: null },
    },
    data: {
      status: DraftStatus.GENERATING,
      submittedAt: null,
    },
  });
  console.log(`[3/3] Reverted ${draftResult.count} ContentDraft rows from PENDING_REVIEW -> GENERATING.`);
  console.log(`        (The content is real AI output — only the status implies operator submitted, which they didn't.)`);

  console.log("\n=== Cleanup complete — only legitimate TC data remains ===\n");
  await prisma.$disconnect();
})().catch((err) => {
  console.error("FAILED:", err);
  process.exit(1);
});
