import type {
  CapabilityContract,
  CapabilityRequirement,
  ProductCapabilityKey,
} from "@/lib/products/capabilities/types";

const DAY_MS = 24 * 60 * 60 * 1000;

function requirement(
  value: CapabilityRequirement,
): CapabilityRequirement {
  return Object.freeze(value);
}

export const PRODUCT_CAPABILITY_CONTRACTS: Readonly<
  Record<ProductCapabilityKey, CapabilityContract>
> = Object.freeze({
  "connected-data-foundation": {
    productKey: "connected-data-foundation",
    subjectScopes: ["organization", "property"],
    requirements: [
      requirement({
        key: "verified-scope",
        label: "Verified tenant scope",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["scope.verified"],
        acceptedScope: "either",
        requiredEvidence: ["configuration"],
        proofSummary: "Organization or property scope was verified.",
        blockerSummary: "Verify the organization and property mapping.",
        actionHref: "/admin/clients",
      }),
      requirement({
        key: "connected-source",
        label: "Connected data source",
        kind: "integration",
        satisfaction: "any",
        impact: "required",
        signalKeys: [
          "integration.any_source",
          "integration.appfolio_availability",
          "integration.cursive_pixel",
          "integration.ga4",
          "integration.gsc",
        ],
        acceptedScope: "either",
        requiredEvidence: ["sync"],
        maxEvidenceAgeMs: 3 * DAY_MS,
        proofSummary: "A connected source produced a verified sync.",
        blockerSummary: "Connect and verify at least one leasing data source.",
        actionHref: "/portal/integrations",
      }),
      requirement({
        key: "fresh-scoped-record",
        label: "Fresh scoped record",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["outcome.fresh_scoped_record"],
        acceptedScope: "either",
        requiredEvidence: ["record"],
        maxEvidenceAgeMs: 3 * DAY_MS,
        proofSummary: "A fresh record landed in the verified scope.",
        blockerSummary: "Run a source sync and verify a correctly scoped record.",
        actionHref: "/portal/integrations",
      }),
    ],
  },
  "lead-to-lease-attribution": {
    productKey: "lead-to-lease-attribution",
    subjectScopes: ["organization", "property"],
    requirements: [
      requirement({
        key: "lead-source",
        label: "Lead source evidence",
        kind: "integration",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["integration.lead_source"],
        acceptedScope: "either",
        requiredEvidence: ["record"],
        proofSummary: "A lead retained defensible source evidence.",
        blockerSummary: "Capture a lead with verified source evidence.",
        actionHref: "/portal/leads",
      }),
      requirement({
        key: "downstream-outcome",
        label: "Downstream leasing outcome",
        kind: "integration",
        satisfaction: "all",
        impact: "degraded",
        signalKeys: ["integration.downstream_outcome"],
        acceptedScope: "either",
        requiredEvidence: ["record"],
        proofSummary: "A downstream application or lease signal was verified.",
        blockerSummary: "Connect an application or lease outcome source.",
        actionHref: "/portal/integrations",
      }),
      requirement({
        key: "attribution-proof",
        label: "Attribution proof",
        kind: "activation",
        satisfaction: "any",
        impact: "required",
        signalKeys: [
          "outcome.attributed_journey",
          "outcome.coverage_measured",
        ],
        acceptedScope: "either",
        requiredEvidence: ["outcome"],
        proofSummary: "A journey or explicit attribution coverage result was verified.",
        blockerSummary: "Produce a traceable journey or measured coverage result.",
        actionHref: "/portal/attribution",
      }),
    ],
  },
  "ai-leasing-chatbot": {
    productKey: "ai-leasing-chatbot",
    subjectScopes: ["property"],
    requirements: [
      requirement({
        key: "chatbot-setup",
        label: "Chatbot configured",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["setup.chatbot_configured"],
        acceptedScope: "exact_property",
        requiredEvidence: ["configuration"],
        proofSummary: "The property chatbot configuration was verified.",
        blockerSummary: "Configure this property's chatbot and knowledge.",
        actionHref: "/portal/chatbot",
      }),
      requirement({
        key: "notification-recipient",
        label: "Lead notification recipient",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["setup.notification_recipient"],
        acceptedScope: "either",
        requiredEvidence: ["configuration"],
        proofSummary: "A lead notification recipient was configured.",
        blockerSummary: "Configure a recipient for captured leads.",
        actionHref: "/portal/settings",
      }),
      requirement({
        key: "chatbot-origin",
        label: "Verified chatbot origin",
        kind: "integration",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["integration.chatbot_origin"],
        acceptedScope: "exact_property",
        requiredEvidence: ["connection"],
        proofSummary: "The chatbot origin was verified for this property.",
        blockerSummary: "Verify the property domain and chatbot origin.",
        actionHref: "/portal/chatbot",
      }),
      requirement({
        key: "chatbot-truth-test",
        label: "Leasing truth test",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["outcome.chatbot_truth_test"],
        acceptedScope: "exact_property",
        requiredEvidence: ["outcome"],
        maxEvidenceAgeMs: 14 * DAY_MS,
        proofSummary: "A controlled transcript passed the property truth test.",
        blockerSummary: "Verify property facts and availability in a controlled chat.",
        actionHref: "/portal/chatbot",
      }),
      requirement({
        key: "live-chatbot-proof",
        label: "Live chatbot outcome",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: [
          "outcome.chatbot_conversation",
          "outcome.chatbot_lead",
          "outcome.notification_delivered",
        ],
        acceptedScope: "exact_property",
        requiredEvidence: ["outcome"],
        maxEvidenceAgeMs: 14 * DAY_MS,
        proofSummary: "A live conversation captured and delivered a property lead.",
        blockerSummary: "Run the controlled chatbot lead and notification test.",
        actionHref: "/portal/chatbot",
      }),
    ],
  },
  "conversion-offers": {
    productKey: "conversion-offers",
    subjectScopes: ["property"],
    requirements: [
      requirement({
        key: "offer-setup",
        label: "Published offer",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["setup.offer_published"],
        acceptedScope: "exact_property",
        requiredEvidence: ["configuration"],
        proofSummary: "A property offer is published.",
        blockerSummary: "Publish an offer for this property.",
        actionHref: "/portal/popups",
      }),
      requirement({
        key: "offer-proof",
        label: "Offer conversion proof",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["outcome.offer_impression", "outcome.offer_conversion"],
        acceptedScope: "exact_property",
        requiredEvidence: ["outcome"],
        proofSummary: "A property impression and conversion were recorded.",
        blockerSummary: "Verify an impression and conversion on the live site.",
        actionHref: "/portal/popups",
      }),
    ],
  },
  "reputation-rescue": {
    productKey: "reputation-rescue",
    subjectScopes: ["property"],
    requirements: [
      requirement({
        key: "reputation-source",
        label: "Reputation source",
        kind: "integration",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["integration.reputation_source"],
        acceptedScope: "exact_property",
        requiredEvidence: ["connection"],
        proofSummary: "A property reputation source was verified.",
        blockerSummary: "Verify this property on a supported reputation source.",
        actionHref: "/portal/reputation",
      }),
      requirement({
        key: "reputation-identity",
        label: "Property reputation identity",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["setup.reputation_identity"],
        acceptedScope: "exact_property",
        requiredEvidence: ["configuration"],
        proofSummary: "The source identity is mapped to this property.",
        blockerSummary: "Map the supported source to this exact property.",
        actionHref: "/portal/reputation",
      }),
      requirement({
        key: "reputation-proof",
        label: "Reputation workflow proof",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["outcome.reputation_baseline", "outcome.reputation_action"],
        acceptedScope: "exact_property",
        requiredEvidence: ["outcome"],
        proofSummary: "A baseline scan produced a completed reputation action.",
        blockerSummary: "Run a baseline scan and complete one supported action.",
        actionHref: "/portal/reputation",
      }),
    ],
  },
  "search-opportunity-engine": {
    productKey: "search-opportunity-engine",
    subjectScopes: ["property"],
    requirements: [
      requirement({
        key: "search-source",
        label: "Search intelligence source",
        kind: "integration",
        satisfaction: "any",
        impact: "required",
        signalKeys: [
          "integration.ga4",
          "integration.gsc",
          "integration.search_intelligence",
        ],
        acceptedScope: "exact_property",
        requiredEvidence: ["sync"],
        maxEvidenceAgeMs: 3 * DAY_MS,
        proofSummary: "Fresh property search intelligence was verified.",
        blockerSummary: "Connect and sync GA4, GSC, or search intelligence.",
        actionHref: "/portal/seo",
      }),
      requirement({
        key: "search-opportunity-proof",
        label: "Search opportunity proof",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["outcome.search_baseline", "outcome.search_opportunity"],
        acceptedScope: "exact_property",
        requiredEvidence: ["outcome"],
        proofSummary: "A property baseline produced a reviewable opportunity.",
        blockerSummary: "Complete a baseline and verify one property opportunity.",
        actionHref: "/portal/seo",
      }),
    ],
  },
  "monday-action-brief": {
    productKey: "monday-action-brief",
    subjectScopes: ["organization"],
    requirements: [
      requirement({
        key: "brief-recipient",
        label: "Brief recipient",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["setup.brief_recipient"],
        acceptedScope: "organization",
        requiredEvidence: ["configuration"],
        proofSummary: "A brief recipient was configured.",
        blockerSummary: "Configure a recipient for the weekly brief.",
        actionHref: "/portal/reports",
      }),
      requirement({
        key: "brief-source",
        label: "Fresh brief source",
        kind: "integration",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["integration.any_source"],
        acceptedScope: "organization",
        requiredEvidence: ["sync"],
        maxEvidenceAgeMs: 7 * DAY_MS,
        proofSummary: "A fresh organization data lane can support the brief.",
        blockerSummary: "Connect and sync at least one brief data source.",
        actionHref: "/portal/integrations",
      }),
      requirement({
        key: "brief-proof",
        label: "Delivered brief proof",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: [
          "outcome.brief_generated",
          "outcome.brief_delivered",
          "outcome.brief_opened",
        ],
        acceptedScope: "organization",
        requiredEvidence: ["delivery"],
        proofSummary: "A generated brief was delivered and opened.",
        blockerSummary: "Generate and verify delivery of the weekly brief.",
        actionHref: "/portal/reports",
      }),
    ],
  },
  "website-build": {
    productKey: "website-build",
    subjectScopes: ["property"],
    requirements: [
      requirement({
        key: "website-scope",
        label: "Approved website scope",
        kind: "setup",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["setup.website_scope_approved"],
        acceptedScope: "exact_property",
        requiredEvidence: ["configuration"],
        proofSummary: "The property website scope was approved.",
        blockerSummary: "Approve scope, content, domain access, and timeline.",
        actionHref: "/admin/website-builds",
      }),
      requirement({
        key: "website-domain",
        label: "Verified website domain",
        kind: "integration",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["integration.verified_domain"],
        acceptedScope: "exact_property",
        requiredEvidence: ["health"],
        proofSummary: "The live domain is verified for this property.",
        blockerSummary: "Verify the live domain belongs to this property.",
        actionHref: "/admin/website-builds",
      }),
      requirement({
        key: "website-proof",
        label: "Live measured website",
        kind: "activation",
        satisfaction: "all",
        impact: "required",
        signalKeys: ["outcome.website_live", "outcome.measurement_verified"],
        acceptedScope: "exact_property",
        requiredEvidence: ["outcome"],
        proofSummary: "The website is live with verified measurement.",
        blockerSummary: "Launch the approved site and verify measurement.",
        actionHref: "/admin/website-builds",
      }),
    ],
  },
});
